#!/bin/zsh

python convtest1D.py -a -3.1415 -b 3.0 --D1 "AE4" --D2 "E4" -l 0 10
python convtest1D.py -a -3.1415 -b 3.0 --D1 "AE4" --D2 "E4" -l 1 10
python convtest1D.py -a -3.1415 -b 3.0 --D1 "AE4" --D2 "E4" -l 2 10
python convtest1D.py -a -3.1415 -b 3.0 --D1 "AE4" --D2 "E4" -l 3 10
python convtest1D.py -a -3.1415 -b 3.0 --D1 "AE4" --D2 "E4" -l 4 10
